### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by oxr463** [GKernelCI/Glava#1]
Where was this forked from? The licensing for this repository is not as straight forward since it has so many contributors.

EDIT: Looks like it came from here (https://github.com/kernelci/lava-docker).

**Comment by oxr463** [comment]
See: https://github.com/kernelci/lava-docker/issues/132

**Comment by aliceinwire** [comment]
good catch!

**Comment by aliceinwire** [comment]
fixed upstream
